In [45]:
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw 

import pandas as pd

import os

import copy

In [157]:
base_cover = Image.new('L', (224, int(224*1.6)), color=(128))

In [169]:
data = pd.read_csv('rows0-1000.csv')

In [173]:
author_text, name_text = data.name[949].split(':')

In [172]:
data

id                                   link  \
0    451006  https://www.labirint.ru/books/451006/   
1    786953  https://www.labirint.ru/books/786953/   
2    840898  https://www.labirint.ru/books/840898/   
3    614463  https://www.labirint.ru/books/614463/   
4    869738  https://www.labirint.ru/books/869738/   
..      ...                                    ...   
947  891292  https://www.labirint.ru/books/891292/   
948  891584  https://www.labirint.ru/books/891584/   
949  891889  https://www.labirint.ru/books/891889/   
950  885411  https://www.labirint.ru/books/885411/   
951  872576  https://www.labirint.ru/books/872576/   

                                           name  rate  \
0             Роберт Стивенсон: Остров Сокровищ  9.38   
1    Жюль Верн: Вокруг света в восемьдесят дней  8.26   
2           Тур Хейердал: Экспедиция "Кон-Тики"  8.33   
3        Артур Дойл: Приключения Шерлока Холмса  9.06   
4          Артур Дойл: Записки о Шерлоке Холмсе  9.07   
..                                          ...   ...   
947               James Crumley: The Wrong Case  0.00   
948            Salvatore Scibona: The Volunteer  0.00   
949                Brian Moore: Lies Of Silence  0.00   
950           Don Winslow: The Gentlemen's Hour  0.00   
951                  Артур Дойл: Затерянный мир  9.09   

                                           description  \
0     Знаменитый роман Роберта Льюиса Стивенсона в ...   
1    "Вокруг книги" - это лучшие произведения миров...   
2    Отважный человек, нестандартно мыслящий, самоо...   
3    Интерактивное комментированное издание рассказ...   
4    В книгу вошли пять рассказов Артура Конан Дойл...   
..                                                 ...   
947  Milo Milodragovitch is a once-successful divor...   
948  An odyssey of loss and salvation ranging acros...   
949  When Michael Dillon is ordered by the IRA to p...   
950  Boone Daniels, a laid-back private investigato...   
951  Чтобы снискать благосклонность красавицы Глэди...   

                                               reviews  
0    Есть у меня одна страсть. По нынешним временам...  
1    Позволю себе не разделить восторга предыдущих ...  
2    Наверное, впервые вижу книгу, про которую хоче...  
3    Фотографии сделаны на выставке. Фотографировал...  
4    Вторая книга, наконец-то! Уже и не чаяли, как ...  
..                                                 ...  
947                                                NaN  
948                                                NaN  
949                                                NaN  
950                                                NaN  
951  Любимая книга моей юности - и в таком великоле...  

[952 rows x 6 columns]

In [178]:
from transformers import AutoImageProcessor, AutoModel
from PIL import Image

device = 'cuda'

processor = AutoImageProcessor.from_pretrained('facebook/dinov2-giant')
model = AutoModel.from_pretrained('facebook/dinov2-giant').to(device)

def embed_picture(image):
    inputs = processor(images=image, return_tensors="pt").to(device)
    outputs = model(**inputs)
    embedding = outputs.last_hidden_state.detach().cpu().numpy()[0].flatten()
    return embedding

In [179]:
positions = [((224/2, 224*1.6/1.5), (224/2, 224*1.6/8), 'mm'), ((224/3, 224*1.6/10), (224/10, 224*1.6/1.25), 'la'), ((224/2, 224*1.6/6), (224/2, 224*1.6/2.5), 'mm')]

name_text = '\n'.join(name_text.split(' '))

for color in (0, 255):
    for font in os.listdir('fonts'):
        for name_pos, author_pos, anchor in positions:

            temp_cover = copy.copy(base_cover)
            draw = ImageDraw.Draw(temp_cover)

            name_font = ImageFont.truetype(f"fonts/{font}", 30)
            author_font = ImageFont.truetype(f"fonts/{font}", 20)

            draw.text(name_pos, name_text, fill=(color), font=name_font, anchor=anchor)
            draw.text(author_pos, author_text, fill=(color), font=author_font, anchor=anchor)
            
            display(embed_picture(temp_cover.resize((224, 224))))

array([ 3.3943758 ,  0.6206146 ,  1.252059  , ...,  0.07052863,
        1.14376   , -0.36159754], dtype=float32)

array([ 2.7009964 ,  0.06892364,  1.0995466 , ...,  0.09858808,
        1.2046993 , -0.9241832 ], dtype=float32)

array([2.6105618 , 1.2826306 , 1.2696425 , ..., 0.05532897, 0.99223626,
       0.12127715], dtype=float32)

array([ 2.552406  ,  0.29317614,  1.525908  , ..., -0.08609925,
        0.98055536, -0.6723411 ], dtype=float32)

array([ 1.9050411 ,  0.03789985,  1.6799786 , ..., -0.17102335,
        1.2290604 , -1.17312   ], dtype=float32)

array([ 2.1082182 ,  1.1860244 ,  1.479447  , ..., -0.0907946 ,
        1.0515964 , -0.18405072], dtype=float32)

array([ 2.0197546 ,  1.9771969 ,  0.59277076, ...,  0.09568849,
        0.9313459 , -0.31965327], dtype=float32)

array([ 2.2185845 ,  1.5456179 ,  0.43320012, ...,  0.09759481,
        1.0695477 , -0.9102079 ], dtype=float32)

array([1.9328874 , 2.873641  , 0.92785835, ..., 0.3097735 , 0.5413167 ,
       0.15664305], dtype=float32)

array([ 2.1482205 ,  0.15758555,  0.66363114, ..., -0.14831193,
        0.35438117, -0.684064  ], dtype=float32)

array([ 2.0860088 , -0.1506055 ,  0.66404647, ..., -0.01335309,
        0.59352356, -1.1281366 ], dtype=float32)

array([ 2.203881  ,  0.38787073,  0.8156545 , ..., -0.0234266 ,
        0.45041507, -0.07046404], dtype=float32)

array([ 2.528711  ,  0.00417989,  0.80898607, ..., -0.24888381,
        0.43777925, -0.8587526 ], dtype=float32)

array([ 2.3255706 , -0.19433232,  0.8359706 , ..., -0.22358315,
        0.6093935 , -1.2493953 ], dtype=float32)

array([ 2.5204992 ,  0.19485939,  0.8341969 , ..., -0.16107455,
        0.45906672, -0.30892155], dtype=float32)

array([ 2.7109427 ,  0.9364412 ,  0.12758696, ..., -0.22475077,
        0.8152358 , -1.1148672 ], dtype=float32)

array([ 3.0800002 ,  1.1555785 , -0.21890436, ..., -0.16378678,
        0.9814571 , -1.3322685 ], dtype=float32)

array([ 2.8169665 ,  1.4518311 ,  0.42718264, ..., -0.13486278,
        0.52368385, -0.24309608], dtype=float32)

In [47]:
os.listdir('fonts')

['DudkaRegular.ttf',
 'KanitCyrillic.otf',
 'LTRemark-Regular.otf',
 'LTSuperior-Regular.otf',
 'TschicholdBold.ttf']